# Generated by Django 4.2.7 on 2023-11-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_alter_product_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='sku_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
