# Generated by Django 4.2.7 on 2023-11-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_productvariant_sku_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='Attribute_Value',
            new_name='attribute_value',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku_id',
            field=models.CharField(default=12, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to='product_variant/images/'),
        ),
    ]
