# Generated by Django 4.2.7 on 2023-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_rename_attribute_value_productvariant_attribute_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_value',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='product_management.attribute_value'),
        ),
    ]
