# Generated by Django 4.2.7 on 2023-11-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_alter_productvariant_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product_variant_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
