# Generated by Django 4.2.7 on 2023-12-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_alter_productvariant_product_variant_slug'),
    ]

    operations = [
    ]
