# Generated by Django 4.2.7 on 2023-12-20 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_auto_20231211_1310'),
        ('order_management', '0003_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='variations',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='discount',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.productvariant'),
        ),
    ]
