# Generated by Django 4.2.7 on 2024-01-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0007_order_cancellation_reason_order_cancellation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(default='Damaged Product', max_length=150),
        ),
    ]
