# Generated by Django 4.2.7 on 2024-01-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_remove_order_cancellation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
