# Generated by Django 4.2.7 on 2024-01-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0010_remove_order_cancel_request_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancel Order Requested', 'Cancel Order Requested')], default='New', max_length=30),
        ),
    ]
