# Generated by Django 4.2.7 on 2024-01-17 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order_management', '0011_remove_cancellationrequest_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='admin_comments',
        ),
        migrations.RemoveField(
            model_name='cancellationrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='reason',
            field=models.TextField(default='damaged'),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='New', max_length=10),
        ),
    ]
