# Generated by Django 4.2.7 on 2024-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0014_cancellationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancellationRequest',
        ),
    ]
