# Generated by Django 4.2.7 on 2023-12-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='email',
            field=models.EmailField(default='ismathrm(@gmail.com)', max_length=100),
        ),
        migrations.AlterField(
            model_name='addressbook',
            name='phone',
            field=models.CharField(default=9633018297, max_length=15),
        ),
    ]
