# Generated by Django 4.2.7 on 2024-01-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_auto_20231211_1310'),
        ('home', '0008_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitems',
            options={'verbose_name': 'Wishlist Item', 'verbose_name_plural': 'Wishlist'},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='wishlist_items', to='product_management.productvariant'),
        ),
        migrations.AlterField(
            model_name='wishlistitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.productvariant'),
        ),
    ]
