# Generated by Django 4.2.7 on 2024-01-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_wishlist_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wishlistitems',
            options={},
        ),
        migrations.RenameField(
            model_name='wishlistitems',
            old_name='product',
            new_name='product_variant',
        ),
    ]
